project:
  type: website
  output-dir: "."
website:
  title: "H.Ahmadzai | Agricultural Economist"
  site-url: "https://ahmadzaihayat.github.io"
  favicon: images/yellow-duck-512.png
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: bio.qmd
        text: bio
      - href: research.qmd
        text: research
      - href: cv.qmd
        text: cv
      - href: mylibrary.qmd
        text: my library
      - text: more
        menu:
          - href: teaching.qmd
            text: teaching
          - href: "https://scholar.google.com/citations?user=iTDaZLcAAAAJ&hl=en"
            text: google scholar
          - href: "https://orcid.org/0000-0001-9766-7052i"
            text: orcid
         #   - href: "https://www.researchgate.net/profile/Hayatullah_Ahmadzai"
          #    text: researchgate
          - href: "https://www.linkedin.com/in/ahmadzaihayat"
            text: linkedin
          # - href: https://tweeds.io
           # text: tweeds
          # - href: stuff.qmd
           #  text: stuff
          # - href: links.qmd
           #  text: links
   #  right:
      # - icon: github
       #  href: https://github.com/edrubin
      # - icon: camera2
       #  href: photos.html
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header:
      text: |
        <meta name="google-site-verification" content="b2mR1diKke69PKpsTkPBo7VHprsTT1z7K9PfUlnl4LI" />
